Eventually, docker usage is now functional.

diff --git a/DockerContext/Dockerfile b/DockerContext/Dockerfile
--- a/DockerContext/Dockerfile
+++ b/DockerContext/Dockerfile
@@ -2,21 +2,18 @@ FROM python:3.10-buster
 
 RUN set -ex \
     && git clone https://github.com/EricBoix/jj_doc_Collecting_Gold_Dust.git \
-    && mv jj_doc_Collecting_Gold_Dust/ jj_doc_Collecting_Gold_Dust.git \
-    && cd jj_doc_Collecting_Gold_Dust.git
-# FIXME: we should be pinning the version
-#    && git checkout 444b50086c
+    # Rename archive for clear context when debugging/fixing in container
+    && mv jj_doc_Collecting_Gold_Dust/ jj_doc_Collecting_Gold_Dust.git
+    # FIXME: we should be pinning the version with e.g.
+    # && cd jj_doc_Collecting_Gold_Dust.git \
+    # && git checkout 444b50086c
 
 WORKDIR jj_doc_Collecting_Gold_Dust.git/Convert
-RUN set -ex \
-    && pip install -r requirements.txt
+RUN set -ex && pip install -r requirements.txt
 
-RUN ls -al
-
+# Systematically run tests at build time (fail often, fail early)
 RUN set -ex \
     && pip install -r requirements-dev.txt \
     && pytest test_main.py
-
-COPY ./entrypoint.py ./
 
 ENTRYPOINT ["python3", "./main.py"]
